// Command genprotocol generates the shared, private native handle ABI constants.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

type enumValue struct {
	Name string
	ID   uint32
	// Bridge names the JavaScript-facing method for operations that both the
	// Node addon and the WASM export table must implement.
	Bridge string
}
type capability struct {
	Name                  string
	Bit                   uint32
	Implemented, Required bool
}
type protocol struct {
	Major, Minor, MaxBatchSize                                      uint32
	Capabilities                                                    []capability
	Fields, Operations, NodeKinds, PatchKinds, EventKinds, Statuses []enumValue
}

var identifier = regexp.MustCompile(`^[A-Z][A-Za-z0-9]*$`)
var bridgeMethod = regexp.MustCompile(`^handle[A-Z][A-Za-z0-9]*$`)

func generate(data []byte) (map[string][]byte, error) {
	var p protocol
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&p); err != nil {
		return nil, err
	}
	if err := decoder.Decode(new(any)); err != io.EOF {
		return nil, fmt.Errorf("trailing protocol JSON")
	}
	if p.Major == 0 || p.MaxBatchSize == 0 || len(p.Capabilities) == 0 {
		return nil, fmt.Errorf("invalid protocol metadata")
	}
	var advertised, required uint32
	names := map[string]bool{}
	bits := map[uint32]bool{}
	for _, cap := range p.Capabilities {
		if !identifier.MatchString(cap.Name) || names[strings.ToUpper(cap.Name)] || cap.Bit >= 32 || bits[cap.Bit] || (cap.Required && !cap.Implemented) {
			return nil, fmt.Errorf("invalid capability %q", cap.Name)
		}
		names[strings.ToUpper(cap.Name)] = true
		bits[cap.Bit] = true
		if cap.Implemented {
			advertised |= uint32(1) << cap.Bit
		}
		if cap.Required {
			required |= uint32(1) << cap.Bit
		}
	}
	ts := fmt.Sprintf("// Code generated by genprotocol; DO NOT EDIT.\nexport const HANDLE_PROTOCOL_MAJOR = %d;\nexport const HANDLE_PROTOCOL_MINOR = %d;\nexport const HANDLE_MAX_BATCH_SIZE = %d;\nexport const HANDLE_REQUIRED_CAPABILITIES = [%d] as const;\nexport const HANDLE_CAPABILITIES = [%d] as const;\n", p.Major, p.Minor, p.MaxBatchSize, required, advertised)
	c := fmt.Sprintf("/* Code generated by genprotocol; DO NOT EDIT. */\n#ifndef PCGO_HANDLE_PROTOCOL_H\n#define PCGO_HANDLE_PROTOCOL_H\n#define HANDLE_PROTOCOL_MAJOR %d\n#define HANDLE_PROTOCOL_MINOR %d\n#define HANDLE_MAX_BATCH_SIZE %d\n#define HANDLE_CAPABILITIES %du\n", p.Major, p.Minor, p.MaxBatchSize, advertised)
	g := fmt.Sprintf("// Code generated by genprotocol; DO NOT EDIT.\npackage asthandle\n\nconst (\nProtocolMajor uint32 = %d\nProtocolMinor uint32 = %d\nMaxBatchSize uint32 = %d\nCapabilities uint32 = %d\nRequiredCapabilities uint32 = %d\n", p.Major, p.Minor, p.MaxBatchSize, advertised, required)
	for _, cap := range p.Capabilities {
		value := uint32(1) << cap.Bit
		ts += fmt.Sprintf("export const HANDLE_CAPABILITY_%s = %d;\n", strings.ToUpper(cap.Name), value)
		c += fmt.Sprintf("#define HANDLE_CAPABILITY_%s %du\n", strings.ToUpper(cap.Name), value)
		g += fmt.Sprintf("Capability%s uint32 = %d\n", cap.Name, value)
	}
	var bridgeNames []string
	seenBridge := map[string]bool{}
	for _, group := range []struct {
		prefix, goPrefix, goType string
		values                   []enumValue
	}{
		{"FIELD", "Field", "Field", p.Fields}, {"OPERATION", "Operation", "uint32", p.Operations}, {"NODE", "Type", "int32", p.NodeKinds}, {"PATCH", "Patch", "uint32", p.PatchKinds}, {"EVENT", "Event", "uint32", p.EventKinds}, {"STATUS", "Status", "uint32", p.Statuses},
	} {
		if len(group.values) == 0 {
			return nil, fmt.Errorf("empty %s enum", group.prefix)
		}
		seenNames := map[string]bool{}
		seenIDs := map[uint32]bool{}
		for _, value := range group.values {
			name := strings.ToUpper(value.Name)
			if !identifier.MatchString(value.Name) || seenNames[name] || seenIDs[value.ID] || value.ID > 0x7fffffff {
				return nil, fmt.Errorf("invalid %s enum value %q", group.prefix, value.Name)
			}
			seenNames[name] = true
			seenIDs[value.ID] = true
			if value.Bridge != "" {
				if group.prefix != "OPERATION" || !bridgeMethod.MatchString(value.Bridge) || seenBridge[value.Bridge] {
					return nil, fmt.Errorf("invalid bridge method %q", value.Bridge)
				}
				seenBridge[value.Bridge] = true
				bridgeNames = append(bridgeNames, value.Bridge)
			}
			ts += fmt.Sprintf("export const HANDLE_%s_%s = %d;\n", group.prefix, name, value.ID)
			c += fmt.Sprintf("#define HANDLE_%s_%s %d\n", group.prefix, name, value.ID)
			g += fmt.Sprintf("%s%s %s = %d\n", group.goPrefix, value.Name, group.goType, value.ID)
		}
	}
	g += ")\n"
	c += "#endif\n"
	if len(bridgeNames) == 0 {
		return nil, fmt.Errorf("no bridge methods declared")
	}
	// Every runtime bridge (Node addon and WASM export table) must implement
	// exactly this set, so drift in one transport fails generation checks.
	g += "\n// BridgeMethods lists the JavaScript-facing handle methods.\nvar BridgeMethods = []string{\n"
	ts += "export const HANDLE_BRIDGE_METHODS = [\n"
	for _, name := range bridgeNames {
		g += fmt.Sprintf("%q,\n", name)
		ts += fmt.Sprintf("  '%s',\n", name)
	}
	g += "}\n"
	ts += "] as const;\n"
	goSource, err := format.Source([]byte(g))
	if err != nil {
		return nil, err
	}
	return map[string][]byte{"protocol_gen.go": goSource, "../../packages/postcss-go/src/generated/handle-protocol.ts": []byte(ts), "../../packages/postcss-go/native/handle_protocol.h": []byte(c)}, nil
}

func main() {
	check := flag.Bool("check", false, "verify checked-in output without writing")
	flag.Parse()
	data, err := os.ReadFile("protocol.json")
	if err != nil {
		panic(err)
	}
	outputs, err := generate(data)
	if err != nil {
		panic(err)
	}
	for path, output := range outputs {
		if *check {
			existing, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(existing, output) {
				panic("stale generated handle protocol: " + path)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			panic(err)
		}
		if err := os.WriteFile(path, output, 0644); err != nil {
			panic(err)
		}
	}
}
