// Command genprotocol generates the shared, private native handle ABI constants.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	check := flag.Bool("check", false, "verify checked-in output without writing")
	flag.Parse()
	data, err := os.ReadFile("protocol.json")
	if err != nil {
		panic(err)
	}
	var p struct {
		Major, Minor, MaxBatchSize int
		Capabilities               []int
		Fields                     []string
	}
	if err := json.Unmarshal(data, &p); err != nil {
		panic(err)
	}
	ts := fmt.Sprintf("// Code generated by genprotocol; DO NOT EDIT.\nexport const HANDLE_PROTOCOL_MAJOR = %d;\nexport const HANDLE_PROTOCOL_MINOR = %d;\nexport const HANDLE_MAX_BATCH_SIZE = %d;\n", p.Major, p.Minor, p.MaxBatchSize)
	c := fmt.Sprintf("/* Code generated by genprotocol; DO NOT EDIT. */\n#define HANDLE_PROTOCOL_MAJOR %d\n#define HANDLE_PROTOCOL_MINOR %d\n#define HANDLE_MAX_BATCH_SIZE %d\n#define HANDLE_CAPABILITIES %d\n", p.Major, p.Minor, p.MaxBatchSize, p.Capabilities[0])
	g := "// Code generated by genprotocol; DO NOT EDIT.\npackage asthandle\n\nconst (\n"
	for i, field := range p.Fields {
		ts += fmt.Sprintf("export const HANDLE_FIELD_%s = %d;\n", strings.ToUpper(field), i)
		g += fmt.Sprintf("\tField%s Field = %d\n", field, i)
		c += fmt.Sprintf("#define HANDLE_FIELD_%s %d\n", strings.ToUpper(field), i)
	}
	g += ")\n"
	for path, content := range map[string]string{
		"protocol_gen.go": g,
		"../../packages/postcss-go/src/generated/handle-protocol.ts": ts,
		"../../packages/postcss-go/native/handle_protocol.h":         c,
	} {
		output := []byte(content)
		if strings.HasSuffix(path, ".go") {
			output, err = format.Source(output)
			if err != nil {
				panic(err)
			}
		}
		if *check {
			existing, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(existing, output) {
				panic("stale generated handle protocol: " + path)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			panic(err)
		}
		if err := os.WriteFile(path, output, 0644); err != nil {
			panic(err)
		}
	}
}
