// Code generated by genprotocol; DO NOT EDIT.
package asthandle

const (
	FieldProp     Field = 0
	FieldValue    Field = 1
	FieldSelector Field = 2
	FieldName     Field = 3
	FieldParams   Field = 4
	FieldText     Field = 5
)
