// Code generated by genprotocol; DO NOT EDIT.
package asthandle

const (
	ProtocolMajor               uint32 = 2
	ProtocolMinor               uint32 = 4
	MaxBatchSize                uint32 = 4096
	Capabilities                uint32 = 511
	RequiredCapabilities        uint32 = 15
	CapabilityScalarSessions    uint32 = 1
	CapabilityStructuredErrors  uint32 = 2
	CapabilityParseOptions      uint32 = 4
	CapabilityBoundedIds        uint32 = 8
	CapabilityReadOnlyFacade    uint32 = 16
	CapabilityAtomicPatches     uint32 = 32
	CapabilityMutationTraversal uint32 = 64
	CapabilitySourceMaps        uint32 = 128
	CapabilityAsyncLifetime     uint32 = 256
	FieldProp                   Field  = 0
	FieldValue                  Field  = 1
	FieldSelector               Field  = 2
	FieldName                   Field  = 3
	FieldParams                 Field  = 4
	FieldText                   Field  = 5
	FieldImportant              Field  = 6
	OperationProtocolInfo       uint32 = 0
	OperationSessionCount       uint32 = 1
	OperationParse              uint32 = 2
	OperationClose              uint32 = 3
	OperationType               uint32 = 4
	OperationGetField           uint32 = 5
	OperationSetField           uint32 = 6
	OperationWalkDecls          uint32 = 7
	OperationOpenCursor         uint32 = 8
	OperationCursorNext         uint32 = 9
	OperationCloseCursor        uint32 = 10
	OperationReadFields         uint32 = 11
	OperationSetFields          uint32 = 12
	OperationStringify          uint32 = 13
	OperationNewDecl            uint32 = 14
	OperationAppend             uint32 = 15
	OperationDispose            uint32 = 16
	OperationReadSnapshots      uint32 = 17
	OperationApplyPatches       uint32 = 18
	OperationInsertBefore       uint32 = 19
	OperationRemove             uint32 = 20
	OperationClone              uint32 = 21
	OperationPrepend            uint32 = 22
	OperationInsertAfter        uint32 = 23
	OperationReplaceWith        uint32 = 24
	OperationNewRule            uint32 = 25
	OperationNewAtRule          uint32 = 26
	OperationNewComment         uint32 = 27
	OperationSetRaw             uint32 = 28
	OperationGetRaw             uint32 = 29
	OperationStringifyMap       uint32 = 30
	OperationParent             uint32 = 31
	OperationChildCount         uint32 = 32
	OperationChildAt            uint32 = 33
	OperationRefreshSnapshot    uint32 = 34
	OperationStringifyBuilder   uint32 = 35
	OperationQuery              uint32 = 36
	TypeNone                    int32  = 0
	TypeRoot                    int32  = 1
	TypeDocument                int32  = 2
	TypeRule                    int32  = 3
	TypeAtRule                  int32  = 4
	TypeDecl                    int32  = 5
	TypeComment                 int32  = 6
	PatchSetField               uint32 = 0
	PatchAppend                 uint32 = 1
	PatchInsertBefore           uint32 = 2
	PatchRemove                 uint32 = 3
	PatchDispose                uint32 = 4
	PatchClone                  uint32 = 5
	EventEnter                  uint32 = 0
	EventExit                   uint32 = 1
	StatusOK                    uint32 = 0
	StatusInvalidHandle         uint32 = 1
	StatusStaleHandle           uint32 = 2
	StatusClosed                uint32 = 3
	StatusNotContainer          uint32 = 4
	StatusBadField              uint32 = 5
	StatusCursor                uint32 = 6
	StatusParse                 uint32 = 7
	StatusCycle                 uint32 = 8
	StatusExhausted             uint32 = 9
	StatusInvalidArgument       uint32 = 10
	StatusInternal              uint32 = 11
)

// BridgeMethods lists the JavaScript-facing handle methods.
var BridgeMethods = []string{
	"handleProtocolInfo",
	"handleParse",
	"handleClose",
	"handleType",
	"handleGetField",
	"handleSetField",
	"handleWalkDecls",
	"handleOpenCursor",
	"handleCursorNext",
	"handleCloseCursor",
	"handleReadFields",
	"handleSetFields",
	"handleStringify",
	"handleNewDecl",
	"handleAppend",
	"handleDispose",
	"handleReadSnapshots",
	"handleApplyPatches",
	"handleInsertBefore",
	"handleRemove",
	"handleClone",
	"handlePrepend",
	"handleInsertAfter",
	"handleReplaceWith",
	"handleNewRule",
	"handleNewAtRule",
	"handleNewComment",
	"handleSetRaw",
	"handleGetRaws",
	"handleStringifyMap",
	"handleParent",
	"handleChildCount",
	"handleChildAt",
	"handleStringifyBuilder",
	"handleQuery",
}
